name: My GitHub Actions Continuous Integration Workflow

on: [push]  # interesting options: time schedule, e.g. every Monday morning at 8AM.

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; fi
      - name: Run pre-commit hooks
        run: |
          pre-commit run --all-files
      - name: Test with pytest
        run: |
          pytest --cov
